### PR TITLE
Update depreciated Infobools

### PR DESCRIPTION
**Pull request by mistervee**
Hi all

Its been a while and thought i would have a play around with madnox on Leia.

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
@mistervee Hi, there!

I did quickly take a peek at this earlier and the only issue I noticed is with ",left" ",right" SubString cause they need to be String.StartsWith and String.EndsWith respectively.

An example would be [here](https://github.com/mikesilvo164/skin.aeon.madnox/pull/22/files#diff-862c3fa368c55152470ba26d28d79ea8R337).

I cannot speak to how Dr. Mike feels but you do have Push rights to this repository and I feel that if you want to add something it is appreciated so please feel free to do so.

Haven't heard from you in awhile so I hope all is well with you and yours?

**Comment by MadMikeDoc** [comment]
Hello,

I'm fine with @mistervee having push rights and anyone who has been kind enough to help us now and in the past.

@mikesilvo164, I did see your friendly reminder and then check to see what needed doing and then ran away! I remember trying to fix these in Krypton and not having much luck, probably using the wrong replacement. Do have it planned to go thru and do but if @mistervee has done that or some of it then thank you very much.

Mike

**Comment by mistervee** [comment]
@mikesilvo164 

I will take a look at what you suggested. I did a mass find and replace so i will look a bit more into it.

Atm i didn't really want to push anything to the branch as i am not sure what @MadMikeDoc thoughts are or if any of the general community are using this. Didn't want to mess anything up.

And speaking of messing stuff up probably best not to push this as i just did an update to my repo for madnox and for some reason my last commit (integration of resource addon) has been added to this pull request. Which will mess up video genre icons. I assume this happen due to me not committing the change. Atm I am playing around with reducing the skin size by putting all that extra artwork into resource addons.

All is well thanks mike. Was working on a skin for the past few months but not sure if i want to continue, so here i am.

Hope your not getting to much grief from the kodi community.

**Comment by MadMikeDoc** [comment]
@mistervee ,

I've been looking into that and asking on the forum how you create resource addons but got nowhere on it, just couldn't find how you created one to begin with.

Yes, skin size is an issue. The main place is the genre backgrounds that schimi did and I'm not sure about getting rid of all that after losing schimi, but life goes on doesn't it. Just trying to find some open source genre backgrounds both gray and coloured that are smaller in size to replace with.

I'll hold off on the commit as I didn't think a mass find and replace would work hence why I haven't started the update myself quite yet!

I can take this if you want as it will be a lot of work to change and re-test each existing Substring and I'll start today, honest!

**Comment by mistervee** [comment]
@MadMikeDoc 

In regards to the the resource addon i am working on, the branch on my repo will have changes that will be quite different to what people are used to and separate addons for the extra artwork will need to be downloaded. The current size of the skin is 600mb i am aiming to get it well under 100mb.

Feel free to try out my repo version. I'll upload the genre resource addons to my repo as that is all is done atm. There is a new section in skin settings 'Artwork' in skin settings.

Feedback would be great to see if you approve of the method.

Give me about 10-20min.

**Comment by MikeSiLVO** [comment]
Fuck me I need to sleep... I hate Insomnia 😦

This PR can be merged minus the addition that @mistervee was testing with resource addons.
I did not have a chance to look at that commit.

The best way to do the SubString IMHO is to search for ,left and ,right then change the start of the condition to either String.StartsWith or String.EndsWith. It will take some time but could be done in a few hours or so, maybe less. Time is not making much sense to me ATM...

@mistervee The last commit was added because you did not switch branches before pushing to your forked repo... I hope that makes sense cause I am too drunk/tired to be more specific 😏

Any questions/issues/ whatever, I am here for you guys... Just I'll be "here" sometime tomorrow or Saturday cause I just realized I got plans tomorrow.

Anyhoo time for me to go night night...

**Comment by mistervee** [comment]
@mikesilvo164 

Just checked and as you suggested i didn't switch branches.

Rest up and don't for get a hair of the dog will help with that headache in the morning. :grin:

**Comment by mistervee** [comment]
@MadMikeDoc 

Genre icon resource addon uploaded to my repo. You will need to enable it in the addon settings once installed.

BTW: not a great deal of skin changes for leia. This should mostly work on Jarvis.

Edit: Just re-read you last comment in regards removing the background. The existing icons and backgrounds will not be removed, only moved to a image plugin and submitted to the kodi repo with full credits to schimi so they can be used in any skin. (that is if i get your stamp of approval)

With the mass find and replace i did a similar thing with silvo. (and i think mike pulled me up on the same  thing though - starts with ends with). Took about 10 min with notepad++. I opened all the skin xml's at once and searched all open files so i could quickly check what it found so i didn't overwrite anything that it shouldn't. Then if all was ok 'find and replace all" in all open documents. I am using sublime text 95% of the time though.

**Comment by MadMikeDoc** [comment]
@mistervee 

You're good to go with the genre icons image resource, thanks again. If you have the time can you send me a PM with info on doing it as I might place all icons in image resource packs although not sure it can be done for all, will have to look at code and see if changes are needed?

Is the PR good to go then or you have to do startwith / endswith changes? or are they still needing to be done?

**Comment by bartolomesoriano** [comment]
Hello all,

Just to clarify, all Substring, left need to be replaced by string.startswith, and all Substring, right need to be replaced by string.endswith, correct? If so, then there are several instances in this PR that were not done that way.  I understand that this is due to the example @mikesilvo164 provided that shows a string.contains with a right argument.  Please check this before merging.  Thanks.

**Comment by bartolomesoriano** [comment]
Also, I really like the idea of using the resource image add-ons.  Any way that I can help more or any testing you all need, you can count on me! I have both Krypton and Leia environments available for testing.

**Comment by mistervee** [comment]
@MadMikeDoc 

Something to think about though is the studio/record label logos. Possibly madnox has more than what the kodi repo version does? Could be worth checking and doing a PR for those.

For the image packs
resource.images.skinbackgrounds
resource.images.skinicons - there are a lot in the extras folder might need some trimming down these are for the home screen menu
resource.images.musicgenreicons
resource.images.musicgenrefanart
resource.images.moviegenreicons -Done
resource.images.moviegenrefanart
resource.images.weatherfanart
resource.images.weathericons
resource.images.languageflags
resource.images.mediaflags - No one has done this in the repo can be a first

For all of these that is about 400mb+. Not sure what else could be added to the repo?

@bartolomesoriano 

As i understand that is the case. I am going to close the PR as i dont think it can be merged atm. I did rush through the updates.

Thanks Testing will be needed in the coming weeks.

**Pull request closed without merging**
